export default {
    ENABLE_PRICE_ALERT: 'ENABLE_PRICE_ALERT',
    DISABLE_PRICE_ALERT: 'DISABLE_PRICE_ALERT',
    DELETE_PRICE_ALERT: 'DELETE_PRICE_ALERT',
    FETCH_PRICE_ALERT: 'FETCH_PRICE_ALERT',
}