export default {
    ENABLE_PIN: 'ENABLE_PIN',
    ENABLE_FINGERPRINT: 'ENABLE_FINGERPRINT',
    DISABLE_PIN: 'DISABLE_ENABLE_PIN',
    DISABLE_FINGERPRINT: 'DISABLE_ENABLE_FINGERPRINT',
    ENABLE_TWO_FACTOR_AUTH: 'ENABLE_TWO_FACTOR_AUTH',
    DISABLE_TWO_FACTOR_AUTH: 'DISABLE_TWO_FACTOR_AUTH',
}