const newsApi = [
    {title: 'UnikoinGold ICO', type: 'AD', body: 'Decentralized esports betting and utility token powered by the Ethereum blockchain. The public crowdsale is now live.', link: { type: 'external', uri: 'https://unikoingold.com/sale' }, image: 'https://icodrops.com/wp-content/uploads/2017/09/cdXhU4Qc_400x400-150x150.jpg', format: 'IMAGE_RIGHT'},
    {title:'Cryptocoin News', type: 'ARTICLE', body: 'Ethereum Price Surpasses $340 for the First Time since August', link: { type: 'external', 'uri': 'https://www.cryptocoinsnews.com/ethereum-price-surpasses-340-first-time-since-august/', params: null}, image: '', format: 'TEXT'},
    // {title:'Announcement', type: '', body: 'Update the app to see charts!', link: null, image: '', format: 'TEXT_CENTER'},
    {title:'Coindesk', type: 'ARTICLE', body: 'Ripio Raises $31 Million in Private Ethereum Token Sale', link: { type: 'external', 'uri': 'https://www.coindesk.com/ripio-raises-31-million-private-ethereum-token-sale/', params: null}, image: '', format: 'TEXT'},
    {title:'Fortune', type: 'ARTICLE', body: 'Why Fidelity Is Mining Bitcoin and Ethereum', link: { type: 'external', 'uri': 'http://fortune.com/2017/10/06/fidelity-bitcoin-ethereum/', params: null}, image: '', format: 'TEXT'},
    {title: 'Aeron ICO', type: 'AD', body: 'Here & now you can contribute to the new aviation safety solution, saving people\'s lives all around the world.', link: { type: 'external', uri: 'https://tokensale.aeron.aero/register/' }, image: 'https://icodrops.com/wp-content/uploads/2017/09/photo_2017-09-24_03-09-28-150x150.jpg', format: 'IMAGE_RIGHT'},
    // {title: null, type: '', body: 'Video comes here', link: { type: 'video', uri: '' }, format: 'VIDEO'},
    {title:'The Merkle', type: 'ARTICLE', body: 'Ethereum Price Is on Target to Hit $400 in the Near Future', link: { type: 'external', 'uri': 'https://themerkle.com/ethereum-price-is-on-target-to-hit-400-in-the-near-future/', params: null}, image: '', format: 'TEXT'},
    {title:'Newsweek', type: 'ARTICLE', body: 'Blockchain Used To Sell Real Estate For The First Time', link: { type: 'external', 'uri': 'http://www.newsweek.com/blockchain-sell-real-estate-first-time-ethereum-682982', params: null}, image: '', format: 'TEXT'},
    // {title: null, type: 'AD', link: null, image: 'https://fs.bitcoinmagazine.com/img/images/doge_ico.width-800.jpg', format: 'IMAGE'},
    {title:'The Next Web', type: 'ARTICLE', body: 'Russians have invented a high-tech heater that also mines Ethereum', link: { type: 'external', 'uri': 'https://thenextweb.com/tech/2017/10/13/russian-ethereum-heater-cryptominer/', params: null}, image: '', format: 'TEXT'},
    {title:'LAToken ICO', type: 'AD', body: 'Blockchain protocol and platform for tokenizing and trading traditional assets.', link: { type: 'external', uri: 'https://sale.latoken.com/'}, image: 'https://icodrops.com/wp-content/uploads/2017/09/L2SxNgoN_400x400-150x150.jpg', format: 'IMAGE_RIGHT'},
    {title:'Forbes', type: 'ARTICLE', body: 'Here\'s The Man Who Created ICOs And This Is The New Token He\'s Backing', link: { type: 'external', 'uri': 'https://www.forbes.com/sites/laurashin/2017/09/21/heres-the-man-who-created-icos-and-this-is-the-new-token-hes-backing/', params: null}, image: '', format: 'TEXT'},
    {title:'Coindesk', type: 'ARTICLE', body: 'Ethereum First: Investment Product Opens for Trading on Nasdaq Exchange', link: { type: 'external', 'uri': 'https://www.coindesk.com/ethereum-first-investment-product-opens-trading-nasdaq-exchange/', params: null}, image: '', format: 'TEXT'},
];

export default newsApi;